apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

labels:
  - pairs:
      managed-by: cluster-pvg1s1
      region: pvg1
      stack: s1
      cluster: pvgs1
