apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rnacos-cluster-dev.yaml

labels:
  - pairs:
      managed-by: tools-appset
      region: pvg1
      stack: s1
      cluster: pvg1s1
