apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rnacos-cluster-dev.yaml
  - rnacos-cluster-prod.yaml

labels:
  - pairs:
      managed-by: tools-appset
      region: pvg2
      stack: s1
      cluster: pvg2s1
