apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitops-root
    managed-by: manual
spec:
  project: default
  source:
    repoURL: git@github.com:zhimanai/gitops-deploy.git
    targetRevision: HEAD
    path: root-apps/appsets/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - Prune=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
